[project]
name = "Caspar"
version = "0.1.0"
description = ""
authors = [
    {name = "nullqwertyuiop", email = "null@member.fsf.org"},
]
dependencies = [
    "aiohttp>=3.9.3",
    "pydantic>=2.6.4",
]
requires-python = ">=3.11"
license = {text = "MIT"}

[tool.pdm]
distribution = false
